import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/clusters",
    title: "Clusters",
    icon: "mdi mdi-server",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/servers",
    title: $localize`Servers`,
    icon: "mdi mdi-server-minus",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/agents",
    title: $localize`Agents`,
    icon: "mdi mdi-arrange-bring-to-front",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/repos",
    title: $localize`Repositories`,
    icon: "fa fa-code",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/crons",
    title: $localize`Crons`,
    icon: "fa fa-clock",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/jobs",
    title: $localize`Jobs`,
    icon: "mdi mdi-backburger",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/configs",
    title: $localize`Configs`,
    icon: "fa fa-cog",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/exit",
    title: $localize`Sign out`,
    icon: "fa fa-power-off",
    class: "",
    extralink: false,
    submenu: [],
  },
];
