name: pipeline

on:
  push:
    tags:
      - "*"
      
jobs:

  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: create-version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

      - name: show-version
        run: echo "Version to build -> ${{ steps.create-version.outputs.version }}"
  

  build-and-push:
    needs: get-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: ghcr.io/jaime-project/${{ secrets.APP_NAME }}:${{ needs.get-version.outputs.version }}
          platforms: linux/amd64
          build-args: ARG_VERSION=${{ needs.get-version.outputs.version }}

  
